spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batterydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for dev; use 'validate' with Flyway in prod
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false

  # Optional: Logging SQL if needed
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
